import Notification from '@/components/Notification'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
import Slider from '@/components/Slider'
import FeaturedProducts from '@/components/FeaturedProducts'
import Offer from '@/components/Offer'
import Flp from '@/components/Flp'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Notification/>
        <Navbar/>
        
        {children}
        <Flp/>
        <Footer/>
        </body>
    </html>
  )
}
